### ISSUE TITLE
Sprawdzanie po masce konta bankowego w pliku płaskim

### ISSUE THREAD

**Issue by pmarek77** [m4rcelpl/WykazPodatnikow#1]
Witam serdecznie
Czy nie ma błędu podczas sprawdzania konta z maskami?
Chyba jest sprawdzana tylko jedna/pierwsza znalezione maska dla danego banku?

**Comment by m4rcelpl** [comment]
Dzień dobry,
Nie powinno być :)
Ale spotkałem się raz z sytuacją że plik plaski na dany dzień nie miał w ogóle masek.

Proszę podesłać parę NIP i nr konta bankowego który jest źle według Pana weryfikowany to sprawdzę.

**Comment by m4rcelpl** [comment]
Przeanalizowałem kod, powinno działać tak jak jest w specyfikacji. Najpierw biorę numer konta i wyciągam z niego liczby od pozycji 2 do 8. Szukam dopasowanej maski, łącze wszystko hashuje i szukam ponownie w body. Jeśli jest z tym jakiś problem to muszę mieć testowe dane wejściowe, czyli numer konta i nip który na stronie w wykazie jest widoczny a nie znajduje go w pliku płaskim po sprawdzeniu moja biblioteką.

**Comment by pmarek77** [comment]
dla przypadku:
        "XX10201390YYYYXXXXXXXXXXXX",
        "XX10201390YYYYYYYYYXXXXXXX",

pętla znajdzie pierwszą maskę i nie szuka kolejnych, sprawdzi kombinację tylko dla pierwszej

            foreach (var item in flatFileData.maski)
            {
                if (bankBranchNumber.Equals(item.Substring(2, 8), StringComparison.OrdinalIgnoreCase))
                {
                    maskToCompare = item;
                    break;
                }
            }
rozwiązaniem np. stworzenie listy masek, maski posortowane, to żeby nie przechodziło całej listy masek można by ograniczyć szukanie, po znalezieniu grupy
jakaś zmienna tymczasowa FlatFile i pętla dla wyszukanych masek, aż znajdzie, wtedy przerywa
Parę NIP, konto bankowe przesyłam na e-mail

**Comment by m4rcelpl** [comment]
Masz rację, błędnie założyłem że numer konta bankowego może pasować tylko do jednej maski. Poprawię to ASAP i wrzucę nową wersję w ciągu 1-2 dni.

**Comment by m4rcelpl** [comment]
Wrzucona poprawka jako 1.1.9-beta. https://www.nuget.org/packages/WykazPodatnikow.Core/1.1.9-beta
Przy aktualizacji pakietów NuGet aby ta wersja była widoczna należy zaznaczyć opcję "Include prerelease". Proszę przetestować i dać znać.

**Comment by m4rcelpl** [comment]
Naprawione w wersji 1.2.0.
